name: Release Binary Package
on: push

jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v2.3.1
      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1
      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: caches-${{ runner.os }}-release
      - name: Build release artifact
        run: bazelisk build //:rules_kotlin_release
      - name: Create release sha256
        run: shasum -a 256 bazel-bin/rules_kotlin_release.tgz > bazel-bin/rules_kotlin_release.tgz.sha256
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rules_kotlin_release
          path: bazel-out/k8-fastbuild/bin/rules_kotlin_release.tgz*
